begin;
select plan(8);
delete from public.platform_metrics;
insert into auth.users(id,email,email_confirmed_at) values('dddddddd-dddd-4ddd-addd-dddddddddddd','metrics@example.test',now());
select is((select count::integer from public.platform_metrics where metric='confirmed_signups'),1,'confirmed account counted once');
update auth.users set email_confirmed_at=now() where id='dddddddd-dddd-4ddd-addd-dddddddddddd';
select is((select count::integer from public.platform_metrics where metric='confirmed_signups'),1,'confirmation update does not double count');
insert into public.playlist_completions(user_id,playlist_id) select 'dddddddd-dddd-4ddd-addd-dddddddddddd',id from public.playlists where published on conflict do nothing;
insert into public.playlist_completions(user_id,playlist_id) select 'dddddddd-dddd-4ddd-addd-dddddddddddd',id from public.playlists where published on conflict do nothing;
select is((select count::integer from public.platform_metrics where metric='playlist_completions'),1,'duplicate completion counts only new row');
set local role authenticated;
select set_config('request.jwt.claim.sub','dddddddd-dddd-4ddd-addd-dddddddddddd',true);
select lives_ok('select public.record_practice_access()','authenticated event increments');
select throws_ok('select * from public.platform_metrics','42501',null,'client cannot read aggregate counters');
select throws_ok($$select public.increment_platform_metric('confirmed_signups')$$,'42501',null,'client cannot forge confirmation count');
reset role;
select is((select count::integer from public.platform_metrics where metric='practice_accesses'),1,'practice counter contains event only');
set local role anon;
select throws_ok('select public.record_practice_access()','42501',null,'anonymous events rejected');
reset role;
select * from finish();
rollback;
