begin;
select plan(26);
insert into auth.users (id, email) values
 ('aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa', 'a@example.test'),
 ('bbbbbbbb-bbbb-4bbb-abbb-bbbbbbbbbbbb', 'b@example.test');
insert into storage.objects (bucket_id, name) select 'phrase-audio', storage_path from public.audio_variants on conflict do nothing;
insert into public.playlists(id,slug,title,sort_order,published) values ('cccccccc-cccc-4ccc-accc-cccccccccccc','unpublished-test','Unpublished',99,false);
select is((select public from storage.buckets where id='phrase-audio'), false, 'reference bucket is private');
select ok(public.valid_word_timings('[{"word":"Hi","startMs":0,"endMs":5}]'), 'valid cues accepted');
select ok(not public.valid_word_timings('[{"word":"Hi","startMs":5,"endMs":1}]'), 'invalid cues rejected');
select ok(not public.valid_word_timings('[{}]'), 'missing cue fields rejected');
select ok(not public.valid_word_timings('null'), 'null timings rejected');
select ok(not public.valid_word_timings('[{"word":"","startMs":0,"endMs":5}]'), 'empty word rejected');
select ok(not public.valid_word_timings('[{"word":"Hi","startMs":0,"endMs":5},{"word":"there","startMs":4,"endMs":9}]'), 'overlapping cues rejected');
set local role anon;
select throws_ok('select * from public.playlists', '42501', null, 'anon has no catalog grant');
select throws_ok('select * from public.phrases', '42501', null, 'anon has no phrase grant');
select throws_ok('select * from public.audio_variants', '42501', null, 'anon has no variant grant');
select throws_ok('select * from public.playlist_completions', '42501', null, 'anon has no completion grant');
select is((select count(*)::integer from storage.objects where bucket_id='phrase-audio'), 0, 'anon cannot read private objects');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub', 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa', true);
select is((select count(*)::integer from public.playlists), 1, 'A reads published playlist');
select is((select count(*)::integer from public.phrases), 5, 'A reads five phrases');
select is((select count(*)::integer from public.audio_variants), 10, 'archived variants hidden');
select is((select count(*)::integer from storage.objects where bucket_id='phrase-audio'), 10, 'A downloads only active references');
select lives_ok($$insert into public.playlist_completions (user_id,playlist_id) select 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa', id from public.playlists$$, 'A completes own playlist');
select lives_ok($$insert into public.playlist_completions (user_id,playlist_id) select 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa', id from public.playlists on conflict do nothing$$, 'duplicate completion is idempotent');
select is((select count(*)::integer from public.playlist_completions), 1, 'one completion row');
select throws_ok($$insert into public.playlist_completions(user_id,playlist_id) values('aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-accc-cccccccccccc')$$, '42501', null, 'unpublished playlist cannot be completed');
select throws_ok($$insert into public.playlist_completions (user_id,playlist_id) select 'bbbbbbbb-bbbb-4bbb-abbb-bbbbbbbbbbbb', id from public.playlists$$, '42501', null, 'A cannot impersonate B');
select set_config('request.jwt.claim.sub', 'bbbbbbbb-bbbb-4bbb-abbb-bbbbbbbbbbbb', true);
select is((select count(*)::integer from public.playlist_completions), 0, 'B cannot read A completion');
select throws_ok('update public.playlist_completions set completed_at=now()', '42501', null, 'completion is append only');
select throws_ok('delete from public.playlist_completions', '42501', null, 'completion deletion forbidden');
select throws_ok($$insert into storage.objects(bucket_id,name) values('phrase-audio','personal.webm')$$, '42501', null, 'no personal recording uploads');
select throws_ok($$update public.playlists set title='changed'$$, '42501', null, 'catalog is not client writable');
reset role;
select * from finish();
rollback;
